### ISSUE TITLE
Versioning with SemVer

### ISSUE THREAD

**Issue by n1trux** [editorconfig/specification#10]
IMHO, a specification should always have a revision format where application programmers and users alike can see which version of the specification the corresponding programs support.

I recommend [SemVer](https://semver.org/). As a positive example I'd cite [the Matrix.org spec](https://matrix.org/docs/spec/).

Since editorconfig is a pretty small specification, the versioning should be pretty easy. Maybe just slap a v1.0 onto the spec if #2 and #8 are resolved? As there are already implementations of the spec which work somewhat this shouldn't be too risky.

**Comment by xuhdev** [comment]
I agree with you on using SemVer. Some details have been discussed in https://github.com/editorconfig/editorconfig/issues/395

**Comment by xuhdev** [comment]
Since this is a duplication of editorconfig/editorconfig#395, I'm closing this now.
