### ISSUE TITLE
Readthedocs link mentioned in README.md not available

### ISSUE THREAD

**Issue by Philzen** [editorconfig/specification#26]
The link to the built version as mentioned in the README.md (<https://editorconfig-specification.readthedocs.io/en/latest/>) just reads "SORRY - This page does not exist yet."

**Comment by cxw42** [comment]
Thanks for reporting!  Would you like to submit a PR?

**Comment by Philzen** [comment]
Done. :smile_cat: 

Hope this is the one you'd have in mind.

**Comment by cxw42** [comment]
Thank you for the PR!  Looks good to me.  I can't merge it myself, but I think someone will soon.  I appreciate your contribution!

**Comment by Philzen** [comment]
> Thank you for the PR! Looks good to me. I can't merge it myself, but I think someone will soon. I appreciate your contribution!

Welcome, glad to help. I appreciate the editorconfig initiative! :laughing:
