### ISSUE TITLE
Odd grammatical syntax at supported-properties/root

### ISSUE THREAD

**Issue by Atlas48** [editorconfig/specification#30]
The text at the aforementioned point reads:

> **`root`**: special property that should be specified at the top of the file outside of any sections. Set to "true" to stop .editorconfig files search on current file.

As a L1 english speaker, I cannot read the above point, "to stop .editorconfig files search" lacks a definite article, perhaps the author meant ""to stop **the** .editorconfig files search**ing** **the** current file"? What is exactly meant by "current file"?

I'm happy to file a pull request, I just lack the context of what it's referring to, hence why I filed an issue first.

**Comment by cxw42** [comment]
PR open at #60

**Comment by Atlas48** [comment]
> Core

Why this specific terminology?

**Comment by florianb** [comment]
> > Core
> 
> Why this specific terminology?

"Core" is a defined word in the grammar: https://spec.editorconfig.org/#id5
