### ISSUE TITLE
Use editorconfig.org subdomain

### ISSUE THREAD

**Issue by ffes** [editorconfig/specification#34]
It is possible on readthedocs to use a [custom (sub)domain](https://docs.readthedocs.io/en/stable/custom-domains.html) to host the specification. Something like `specifications.editorconfig.org` or just `specs.editorconfig.org` would make it clearer that the specifications are officially linked to the project.

Not sure who has access to the DNS of editorconfig.org, but I guess @xuhdev should be able to add the required CNAME record.

**Comment by xuhdev** [comment]
I believe @treyhunner can do it. @treyhunner  Could you add a CNAME of `spec.editorconfig.org` to `editorconfig-specification.readthedocs.io`? I'll update readthedocs settings once the record is up. Thanks!

**Comment by treyhunner** [comment]
@xuhdev @ffes I added the CNAME record. It looks like there's an SSL error now though.

**Comment by xuhdev** [comment]
Looks like it's working now
