### ISSUE TITLE
How to have a multiline value

### ISSUE THREAD

**Issue by Youssef1313** [editorconfig/specification#35]
Per the current specification, I don't see how (if possible) to include a key-value pair whose value is a multiline string.

If it's not currently possible, is it possible to update the spec to have a way for that?

**Comment by cxw42** [comment]
Multiline key-value pairs are not currently described in the spec.  A particular core or plugin could define its own escaping mechanism for multiline values, but at the cost of portability.

The only mention I see of multiline from a quick search is https://github.com/editorconfig/editorconfig/issues/97#issuecomment-571268809 .

Would you please open a ticket at <https://github.com/editorconfig/editorconfig/issues>?  That is where discussion of the technical content of the spec takes place.  Thanks!  I am going to close this ticket.

**Comment by Youssef1313** [comment]
Thanks @cxw42. I opened https://github.com/editorconfig/editorconfig/issues/481
