### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by rakus** [editorconfig/specification#4]
This issue is opened to discuss the table of content for the specification.

Here is a first shot:

## Introduction

Introduction of the specification.

## File Format

Describes the file format of the `.editorconfig` files. Also a subsection on parsing the file.

## Glob Expressions

Describes the glob syntax used in the section headers in the editorconfig file.

## File Processing

Describes the file name, how they are located and the order of processing the content.

## Supported Properties

Describes the supported properties.

## Recommendations for plugin implementers

How should the plugin behave in certain situations. (e.g ignore unknown
properties, warn on invalid values for known properties).

**Comment by xuhdev** [comment]
I agree with these. We probably also want a definition subsection that defines several concepts, such as "properties," "values," etc. in File Format. I also think the last section for plugin developers should be moved to a page specifically written for developers (Pure users do not need to read the last section).

**Comment by rakus** [comment]
Hmm --- This raises the question: Do we write specs to be read by developer who want to develop editorconfig support for a editor/ide etc or do we want to write a user documentation?

**Comment by cxw42** [comment]
As far as I know, this repo was driven by questions from plugin developers.  I think the existing web site does a good job for user-level documentaiton.

**Comment by xuhdev** [comment]
@cxw42 It seems like most of the content is also applicable to general use (e.g., what is a property when a user sees a list of supported properties?). Since clarifying these matters also helps many users (while they may not raise questions), I think it makes sense to separate them with developer-specific content, at least textually, so that users can avoid the trouble reading them.

**Comment by xuhdev** [comment]
I've updated the content. Would you like to [check it out](https://editorconfig-specification.readthedocs.io/en/latest/)?

**Comment by cxw42** [comment]
Can this issue now be closed?

**Comment by cxw42** [comment]
Closing complete :) .
