### ISSUE TITLE
version tags?

### ISSUE THREAD

**Issue by cdmistman** [editorconfig/specification#40]
[According to the specification](https://github.com/editorconfig/specification/blob/b50ab46018a9d95107ab77763db7fe527ff88b9d/index.rst?plain=1#L253-L257), this repository is supposed to have tags corresponding to each version of the specification, but the tags do not exist in:
- git commit messages
- git tags
- git branches
- GitHub releases
- Changelog

If the version tags could be published, or otherwise changing the communication structure of versioning, that'd be greatly appreciated.

**Comment by xuhdev** [comment]
Thanks, that's a great point. I've added version tags.

(Right now you can only look at `conf.py` history and see the version number bumping there.)
