### ISSUE TITLE
Clarify that spelling_language strings must be exactly two or five characters

### ISSUE THREAD

**Issue by cxw42** [editorconfig/specification#48]
Per #41,
> The format [of a `spelling_language` value] is `ss` or `ss-TT`.

I intended `ss` to stand for exactly two characters and `TT` to stand for exactly two characters.  However, as @gustaphe commented in https://github.com/editorconfig/editorconfig-vim/pull/210#issuecomment-2043070775 , `TT` could be read as a variable standing for any ISO 3166 code.

Update the specification to clarify that `ss` represents exactly two characters and `TT` represents exactly the two characters of an [ISO 3166-1 alpha-2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).  Therefore, a `spelling_lanugage` string as a whole must be exactly two chars (`ss`) or exactly five chars (`ss-TT`).

**Comment by ffes** [comment]
It is always a good thing to clarify things if they turn out to be unclear!

Just a question. I guess the `T` in `TT` stands for territory, but what does the `s` in `ss` stand for?

**Comment by cxw42** [comment]
You know, I can't remember why I picked that! 😆  I would guess either (1)"s" for spelling, or (2)the letter before "t".
