### ISSUE TITLE
"Preview" workflow run fails

### ISSUE THREAD

**Issue by cxw42** [editorconfig/specification#52]
I got a [failure](https://github.com/editorconfig/specification/actions/runs/10873774990/job/30170270751?pr=46#step:2:182) on the "Preview" job.  I think it might be because my PR originates from a fork, or maybe one of the access tokens has expired.  @xuhdev could you please investigate?  Thanks!

**Comment by xuhdev** [comment]
Seems like #57 is the real fix!
