### ISSUE TITLE
Enhancement: Light comment style preference

### ISSUE THREAD

**Issue by mcandre** [editorconfig/specification#6]
Users attempting to quickly toggle on and off code commenting, e.g. for YAML, Python and other whitespace sensitive file formats, will find that the resulting uncommented code may not align with the rest of the file, resulting in errors. EditorConfig could minimize this risk, by allowing for a rule on code comments: How many ASCII space characters to insert between `#` and the beginning of the snippet to comment.

Examples:

```yaml
my:
  # car:
  #   color: "red"
```

vs.

```yaml
my:
  #car:
  #  color: "red"
```

Either style would be fine, as long as our text editors can pick up the fact that a certain number of spaces are treated as leading comment characters, when toggling comments back off.

**Comment by jedmao** [comment]
Is this even a common editor setting? I've never seen it before.

**Comment by jedmao** [comment]
At first glance, I'm thinking this type of thing doesn't belong in EditorConfig, because it's too specific to a particular language. Prove me wrong, I guess, but there hasn't been any response to this thread for months. Closing until more interest is revived.
